ccflags-y += -Idrivers/media/platform/msm/camera_v2_s
ccflags-y += -Idrivers/media/platform/msm/camera_v2_s/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_s/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
