obj-$(CONFIG_MSM_VIDC_V4L2) += vidc/
obj-$(CONFIG_DVB_MPQ) += dvb/

ifeq ($(CONFIG_SEC_S_PROJECT),y)
obj-$(CONFIG_MSMB_CAMERA) += camera_v2_s/
else
obj-$(CONFIG_MSMB_CAMERA) += camera_v2/
endif
obj-y += vcap/
