ccflags-y += -Idrivers/media/platform/msm/camera_v2_s
ccflags-y += -Idrivers/media/platform/msm/camera_v2_s/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_led_flash.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_trigger.o
