ccflags-y += -Idrivers/media/platform/msm/camera_v2_s
ccflags-y += -Idrivers/media/platform/msm/camera_v2_s/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_s/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
